name: varda-env

on: [pull_request, push] 
env:
            NODE_ENV: ${{ secrets.NODE_ENV }}
            WEB3TOKEN: ${{ secrets.WEB3TOKEN }}    

jobs:
  job1:
    ## The type of runner that the job will run on, 
    ## here it runs on ubuntu latest
    runs-on: ubuntu-latest 
    environment: github-pages
    steps:
      - name: step 1
        ## Reference your environment variables
        run: echo "The environment is:${{env.NODE_ENV}}"   

  job2:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: step 1
        ## Another way reference your environment variables
        run: echo "The environment is:$NODE_ENV
